### ISSUE TITLE
implement text ulpoad function

### ISSUE THREAD

**Issue by Rookabu** [nfdi4plants/BOAT-Builder-for-Ontology-ARC-Templates#3]

**Comment by Freymaurer** [comment]
It is propably better to read any text file (.md/.txt/.docx) with the respective js library to html and display that.

Then the logic can be:
1. Select some text with the cursor
![image](https://github.com/nfdi4plants/BOAT-Builder-for-Ontology-ARC-Templates/assets/39732517/2f853ebe-e33d-478a-842f-0fb2ad5e116d)
2. Right-click to open custom context menu 
![image](https://github.com/nfdi4plants/BOAT-Builder-for-Ontology-ARC-Templates/assets/39732517/5f49f25c-15d0-49d5-8e19-ab720de92355)
3. Here we should have functions such as:
  - Add as Key
  - Add as Value
  - Send to Key
  - Send to Value
  
  Key, and Value are WIP names and should be improved for production. "Add" functions create a new annotation, "Send" 
  functions add to current annotation.


This solution makes it way easier to enable BOAT for multiple data types and vastly improves performance for large content files.
